name: build-attest

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      id-token: write
      contents: read
      attestations: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build artifact
        run: cargo build --verbose
      - name: Attest Build Provenance
        uses: actions/attest-build-provenance@v1.3.2
        with:
          subject-path: '${{ github.workspace }}/target'